### ISSUE TITLE
add_price_selection keys

### ISSUE THREAD

**Issue by nbdamian** [whytewaters/api-helper-library#13]
It used to be that when creating a price selection with 2 adults and different with field values, e.g
Adult x1 - Weight 55
Adult x1 - Weight 60
This would be submitted as two separate price selections.
It is now overriding the first when you add the second.
This is caused by the price_selections array key being the price_key.

Has the method on how to do this changed?

**Comment by bumperbox** [comment]
I will check it out and get back to you.

**Comment by bumperbox** [comment]
I will have to rewrite that bit of the helper, it should handle the scenario as per your description

**Comment by bumperbox** [comment]
as per discussed, newer version of api helper is not indexed by price key
