### ISSUE TITLE
Create_function deprecated

### ISSUE THREAD

**Issue by edwardleoni** [whytewaters/api-helper-library#8]
Hey, 
This recent commit:
https://github.com/whytewaters/api-helper-library/commit/b4d74b2918ffcce5a080ae03177f82df3bb7039a

Resulted in me not being able to use your library anymore as it uses deprecated functions
http://php.net/manual/en/function.create-function.php

I was running off an older release, but somehow, I think due to wrong use of tags, this applied to the version I was using as well.

Can someone fix this asap?

**Comment by bumperbox** [comment]
I have removed create_function, we haven't tested the library against php 7.2 yet, if you run into any other compatibility issues please let us know
